name: Backend CI

on:
  push:
    branches:
      - main  # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22] # Test on multiple Node.js versions

    environment: MONGO_URI

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Install dependencies for backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    # Run backend tests
    - name: Run Backend Tests
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: ${{ secrets.PORT }}
      working-directory: ./backend
      run: npm test

    # Install dependencies for frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        df -h
        sudo rm -rf ./build
        npm install
        NODE_OPTIONS=--max_old_space_size=400 npm run build

    # Create .env file for production
    - name: Create .env file
      working-directory: ./backend
      run: |
        touch .env
        echo "${{ secrets.PROD }}" > .env

    # Restart backend with PM2
    - name: Restart Backend
      run: pm2 restart muser-backend || pm2 start backend/server.js --name muser-backend

    # Restart frontend with PM2
    - name: Restart Frontend
      run: pm2 restart muser-frontend || pm2 serve frontend/build 5002 --name muser-frontend --spa

    # Save PM2 process list
    - name: Save PM2
      run: pm2 save